spring:
  application:
    name: nova-bank-auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/nova_bank_auth_db
    username: nova_admin_user
    password: Nova@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: YjM0NjM0YjE2NmQ4NzQ2Y2YxOWJmODFkNjQ4YzQ5N2Q0OWQ2M2Q5YzY1ZmJhN2I0NzA2YzY0ZWQxNTA2M2Q4OA==
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

server:
  port: 8081