spring:
  application:
    name: nova-bank-auth-service

springdoc:
  swagger-ui:
    path: /swagger

jwt:
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

server:
  port: 8081